apiVersion : apps/v1
kind: Deployment
metadata:
  name: "positivemustangaks-aa1a"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "positivemustangaks-aa1a"
  template:
    metadata:
      labels:
        app: "positivemustangaks-aa1a"
    spec:
      containers:
        - name: "positivemustangaks-aa1a"
          image: "akseval.azurecr.io/positivemustangaks"
          ports:
          - containerPort: 80