on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n akseval -g aksevalbf10-rg --location "West US 2" --sku Basic --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n akseval --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n akseval --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n akseval --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: akseval.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t akseval.azurecr.io/positivemustangaks:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push akseval.azurecr.io/positivemustangaks:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_positivemustangaks_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep positive-mustang-aksa819 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace positive-mustang-aksa819`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: positive-mustang-aksa819
        container-registry-url: akseval.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: positivemustdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: positive-mustang-aksa819
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          akseval.azurecr.io/positivemustangaks:${{ github.sha }}
        imagepullsecrets: |
          positivemustdockerauth   
